### ISSUE TITLE
Unable to build under node v7.7.4 

### ISSUE THREAD

**Issue by Saulzi** [Esri/esri-leaflet-renderers#136]
This is because of a third party package used in the build process.. 

```TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/srvlr/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)```

**Comment by jgravois** [comment]
the problem appears to have been caused by karma's dependency on `socket.io` ([ref](https://github.com/munichmakerlab/ewindow_webrtc/issues/3)).

thanks for reporting and my apologies for taking so long to fix.
