### ISSUE TITLE
Hi When deploying a docker the package gives this error and does not render a map

### ISSUE THREAD

**Issue by Mwalima** [Esri/esri-leaflet-renderers#173]
Uncaught TypeError: Cannot read properties of undefined (reading 'addInitHook')
    at esri-leaflet-renderers-debug.js:1186:1
    at Object.5Kqs (esri-leaflet-renderers-debug.js:5:63)
    at t (bootstrap d126f5938059b6ed508e:54:1)
    at Object.NHnr (info.vue:27:33)
    at t (bootstrap d126f5938059b6ed508e:54:1)
    at window.webpackJsonp (bootstrap d126f5938059b6ed508e:25:1)
    at app.5da9700bc295f8dc6fc5.js:1:1

eny suggestions?

**Comment by Mwalima** [comment]
The app is written in vuejs version:
Node version :12.18.0
Npm version: 6.14.5

It also happens without the docker build. Just npm run dev
***@***.***

I send you the package json:

"scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "unit": "jest test/unit/specs --coverage",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs",
    "build": "node build/build.js"
  },
  "dependencies": {
    "arcgis": "^1.0.2",
    "axios": "^0.20.0",
    "esri-leaflet-renderers": "^2.1.3",
    "leaflet": "^1.4.0",
    "proj4leaflet": "^1.0.2",
    "promise-polyfill": "^7.1.2",
    "vue": "^2.5.21",
    "vue-css-donut-chart": "^1.0.2",
    "vue-router": "^3.0.2",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.3.0",
    "node-sass": "^4.12.0",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.20",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.6",
    "semver": "^5.6.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.7.3",
    "vue-style-loader": "^3.0.1",
    "vue-svg-loader": "^0.11.0",
    "vue-template-compiler": "^2.5.21",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.11.3",
    "webpack-merge": "^4.1.5"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

Map.vue:
<template>
  <div id="mapDiv" class="mapDiv"></div>
</template>

<script>
import L from 'leaflet'
import 'proj4leaflet'
import 'esri-leaflet-renderers'
import icon from '../assets/icons/markerpin.svg'
import { mapState, mapMutations } from 'vuex'

export default {
  data () {
    return {
      RD: '',
      map: '',
      zoomVar: ''
    }
  },
  mounted () {
    this.mapGen(this.$route.query)
    this.refreshMaps()
    console.log(this.map.getZoom())
    window.scroll({
      top: 0,
      left: 0,
      behavior: 'smooth'
    })
  },
  props: {
    dakenData: Object,
    experimentData: Object,
    voorkeursData: Object
  },
  methods: {
    ...mapMutations(['setMapsOpen', 'setMapClosed', 'setMapOpen', 'toggleMapsOpen']),
    mapGen: function (query) {
      // const RD = new L.Proj.CRS('EPSG:28992', '+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +towgs84=565.2369,50.0087,465.658,-0.406857330322398,0.350732676542563,-1.8703473836068,4.0812 +no_defs',
      //   {
      //     resolutions: [3440.640, 1720.320, 860.160, 430.080, 215.040, 107.520, 53.760, 26.880, 13.440, 6.720, 3.360, 1.680, 0.840, 0.420, 0.210],
      //     bounds: L.bounds([-285401.92, 22598.08], [595401.9199999999, 903401.9199999999]),
      //     origin: [-285401.92, 22598.08]
      //   }
      // )
      this.map = L.map('mapDiv', {
        center: [query.lat, query.lng],
        zoom: query.zoom,
        maxBounds: L.latLngBounds([52.4, 3.8], [51.4, 5.2])
      })
      const updateRoute = () => {
        console.log(this.map.getZoom())
        this.zoomVar = this.map.getZoom()
        // this.$router.push({query: {lat: Math.ceil(this.map.getCenter().lat * 1000) / 1000, lng: Math.ceil(this.map.getCenter().lng * 1000) / 1000, zoom: this.map.getZoom()}})
      }
      // this.map.on('zoomend', updateRoute)
      // this.map.on('moveend', updateRoute)
      this.map.on('zoomend', updateRoute)

      new L.TileLayer('https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/water/EPSG:3857/{z}/{x}/{y}.png', {
        attribution: 'Map data: <a href=http://www.kadaster.nl>Kadaster</a>',
        minZoom: 9,
        maxZoom: 12
      }).addTo(this.map)
    },
    mapUpdate: function (query) {
      this.map.setView([query.lat, query.lng])
      this.map.setZoom(query.zoom)
    },
    refreshMaps: function () {
      const layersOn = this.mapsOpen
      const range = ['groteDakenMapLayer', 'gemeenteGroteDakenLayer', 'gemeenteKleineDakenLayer', 'experimentenLayer', 'voorkeursLayer', 'opwekLayer']
      const layersOff = range.filter(function (i) {
        return layersOn.indexOf(i) < 0
      })
      layersOff.forEach(map => {
        this.map.removeLayer(this[map])
      })
      layersOn.forEach(map => {
        this.map.addLayer(this[map])
      })
    }
  },
  watch: {
    mapsOpen: function () {
      this.refreshMaps()
    },
    zoomVar () {
      if ((this.mapsOpen.indexOf('gemeenteGroteDakenLayer') !== -1) && this.map.getZoom() >= 12) {
        this.setMapOpen('groteDakenMapLayer')
      } else {
        this.setMapClosed('groteDakenMapLayer')
      }
    },
    '$route' () {
      this.mapUpdate(this.$route.query)
      console.log(this.$route.query)
      if ((this.mapsOpen.indexOf('gemeenteGroteDakenLayer') !== -1) && this.$route.query.zoom >= 12) {
        this.setMapOpen('groteDakenMapLayer')
      } else {
        this.setMapClosed('groteDakenMapLayer')
      }
    },
    zoomLevel: function () {
      this.map.setZoom(6)
    }
  },
  computed: {
    groteDakenMapLayer () {
      return L.tileLayer.wms('https://geoservices.zuid-holland.nl/arcgis/services/', {
        version: '1.3.0',
        format: 'image/png',
        styles: 'default',
        layers: 'Grote daken [meer dan 180 panelen]',
        transparent: true
      })
    },
    opwekLayer () {
      return L.tileLayer.wms('https://geoservices.zuid-holland.nl/arcgis/services/', {
        version: '1.3.0',
        format: 'image/png',
        styles: 'default',
        layers: 'Buurt - Potentiele opbrengst/ha [MWh/jaar] - woningen',
        transparent: true
      })
    },
    gemeenteGroteDakenLayer () {
      const getColor = (d) => {
        return d > this.grootValues[0] ? this.grootColors[0]
          : d > this.grootValues[1] ? this.grootColors[1]
            : d > this.grootValues[2] ? this.grootColors[2]
              : d > this.grootValues[3] ? this.grootColors[3]
                : this.grootColors[4]
      }
      const getStyle = (feature) => {
        return {
          fillColor: getColor(feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.opbrengst_groot_dak']),
          weight: 1,
          opacity: 1,
          fillOpacity: 0.6,
          color: 'grey'
        }
      }

      let map = this.map

      const zoomtoFeature = (e) => {
        map.fitBounds(e.target.getBounds())
      }

      const hoverFeature = (e) => {
        let layer = e.target
        layer.setStyle({
          color: '#000066',
          weight: 2
        })
      }
      const leaveFeature = (e) => {
        geojson.resetStyle(e.target)
      }

      const onEachFeature = (feature, layer) => {
        layer.on({
          click: zoomtoFeature,
          mouseover: hoverFeature,
          mouseout: leaveFeature
        })
      }

      let geojson = L.geoJson(null, {
        style: getStyle,
        onEachFeature: onEachFeature
      }).bindTooltip(function (layer) {
        let percentage = layer.feature.properties['Geo_pub.RUIMTE.ZW_Gerealiseerd_gemeente.opbrengst_sde_mwh'] / layer.feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.opbrengst_groot_dak'] * 100
        percentage = percentage > 0 ? percentage.toLocaleString('nl-NL', { maximumFractionDigits: 2 }) : 0
        return ('<div class="leaflet-tooltip-content"><h1>Gemeentenaam: ' + layer.feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.gm_naam'] + '</h1>' +
        'Percentage gerealiseerd: ' + percentage + '%' +
        '<br> Gerealiseerde opbrengst grote daken: ' + layer.feature.properties['Geo_pub.RUIMTE.ZW_Gerealiseerd_gemeente.opbrengst_sde_mwh'].toLocaleString('nl-NL', { maximumFractionDigits: 2 }) + ' MWh/jaar' +
        '<br> Potentiële opbrengst grote daken: ' + layer.feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.opbrengst_groot_dak'].toLocaleString('nl-NL', { minimumFractionDigits: 0 }) + ' MWh/jaar</div>')
      })
      geojson.addData(this.dakenData)
      return geojson
    },
    gemeenteKleineDakenLayer () {
      const getColor = (d) => {
        return d > this.kleinValues[0] ? this.kleinColors[0]
          : d > this.kleinValues[1] ? this.kleinColors[1]
            : d > this.kleinValues[2] ? this.kleinColors[2]
              : d > this.kleinValues[3] ? this.kleinColors[3]
                : this.kleinColors[4]
      }
      const getStyle = (feature) => {
        return {
          fillColor: getColor(feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.opbrengst_ind']),
          weight: 1,
          opacity: 1,
          fillOpacity: 0.6,
          color: 'grey'
        }
      }

      let map = this.map

      const zoomtoFeature = (e) => {
        map.fitBounds(e.target.getBounds())
      }

      const hoverFeature = (e) => {
        let layer = e.target
        layer.setStyle({
          color: '#000066',
          weight: 2
        })
      }
      const leaveFeature = (e) => {
        geojson.resetStyle(e.target)
      }

      const onEachFeature = (feature, layer) => {
        layer.on({
          click: zoomtoFeature,
          mouseover: hoverFeature,
          mouseout: leaveFeature
        })
      }

      let geojson = L.geoJson(null, {
        style: getStyle,
        onEachFeature: onEachFeature
      }).bindTooltip(function (layer) {
        let percentage = layer.feature.properties['Geo_pub.RUIMTE.ZW_Gerealiseerd_gemeente.opbrengst_kv_mwh'] / layer.feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.opbrengst_ind'] * 100
        percentage = percentage > 0 ? percentage.toLocaleString('nl-NL', { maximumFractionDigits: 2 }) : 0
        return ('<div class="leaflet-tooltip-content"> Gemeentenaam: ' + layer.feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.gm_naam'] +
        '<br>Percentage gerealiseerd: ' + percentage + '%' +
        '<br>Gerealiseerde opbrengst kleine daken: ' + layer.feature.properties['Geo_pub.RUIMTE.ZW_Gerealiseerd_gemeente.opbrengst_kv_mwh'].toLocaleString('nl-NL', { maximumFractionDigits: 2 }) + ' MWh/jaar' +
        '<br>Potentiële opbrengst kleine daken: ' + layer.feature.properties['Geo_pub.RUIMTE.ZW_Potentie_gemeente.opbrengst_ind'].toLocaleString('nl-NL', { minimumFractionDigits: 2 }) + ' MWh/jaar</div>')
      })
      geojson.addData(this.dakenData)
      return geojson
    },
    experimentenLayer () {
      const customicon = L.icon({
        iconUrl: icon,
        shadowUrl: '',
        iconSize: [20, 32],
        iconAnchor: [10, 31]
      })

      const pointToLayer = function (feature, latlng) {
        return new L.Marker(latlng, {icon: customicon})
      }

      let geojson = L.geoJson(null, {
        pointToLayer
      }).bindTooltip(function (layer) {
        return ('<div class="leaflet-tooltip-content"> Experiment: ' + layer.feature.properties.Naam +
        '<br>Vermogen: ' + layer.feature.properties.vermogen + '</div>')
      })

      geojson.addData(this.experimentData)
      return geojson
    },
    // voorkeursLayer () {
    //   return L.tileLayer.wms('https://geoservices.zuid-holland.nl/arcgis/rest/services/Energie/Energie_zonnewijzer/MapServer/WMSServer', {
    //     version: '1.3.0',
    //     format: 'image/png',
    //     // styles: 'style_sld_body,style_sld_body,style_sld_body,style_sld_body,style_sld_body,style_sld_body,style_sld_body',
    //     layers: 'Voorkeurslocaties - Samengesteld',
    //     transparent: true,
    //     // sld: 'https://gist.githubusercontent.com/NieneB/8c07fbef082e9542ff65e64f9023a0ea/raw/1782f44c0dd9675265b0f8f5d871840ecee9872a/sld.xml',
    //     opacity: 0.7
    //   })
    // },
    voorkeursLayer () {
      const getColor = (f) => {
        return f === 'Actieve stortplaatsen' ? '#3E1CAC'
          : f === 'Bouwblok' ? '#37A0C4'
            : f === 'Parkeerplaatsen' ? '#35B33B'
              : f === 'Restruimte langs infra' ? '#B74954'
                : f === 'Voormalig stortplaatsen' ? '#A18822'
                  : f !== 'Restruimte langs infra'
      }
      const getOpacity = (a) => {
        return a === 'Actieve stortplaatsen' ? 1
          : a === 'Bouwblok' ? 1
            : a === 'Parkeerplaatsen' ? 1
              : a === 'Restruimte langs infra' ? 0
                : a === 'Voormalig stortplaatsen' ? 1
                  : a !== 'Restruimte langs infra'
      }

      const getStyle = (feature) => {
        return {
          weight: 1,
          opacity: getOpacity(feature.properties.Voorkeurslocaties),
          color: getColor(feature.properties.Voorkeurslocaties)
        }
      }

      const hoverFeature = (e) => {
        let layer = e.target
        console.log(layer)
      }

      const onEachFeature = (feature, layer) => {
        layer.on({
          mouseover: hoverFeature
        })
      }

      let geojson = L.geoJson(null, {
        style: getStyle,
        onEachFeature: onEachFeature
      })
      geojson.addData(this.voorkeursData)
      return geojson
    },
    ...mapState(['mapsOpen', 'grootColors', 'grootValues', 'kleinColors', 'kleinValues', 'kleinGroot', 'zoomLevel'])
  }
}
</script>

<style lang="sass" scoped>
.mapDiv
  flex: 1
  z-index: 0
  background-color: none !important
</style>

Dakenatlas.vue:
<template>
    <div>
      <div class="map-section">
        <div class="left-navigation">
         <div class="links">
          
          <router-link :to="{path: '/daken/grote', query: { lat: 52.0, lng: 4.4, zoom: 10 }}">Dak opstelling</router-link>
          <router-link :to="{path: '/daken/kleine', query: { lat: 52.0, lng: 4.4, zoom: 10 }}">Grond opstelling</router-link>
          
         </div>
         <router-view class="description">description</router-view>
        </div>
        <Map v-if="dakenData.features && experimentData.features && voorkeursData.features" :dakenData="dakenData" :experimentData="experimentData" :voorkeursData="voorkeursData"></Map>
      </div>
    </div>
</template>

<script>
import Map from '../components/Map'
import { mapState } from 'vuex'
export default {
  components: {
    Map
  },
  computed: {
    ...mapState('data', ['dakenData', 'experimentData', 'voorkeursData'])
  }
}
</script>

<style lang="sass">
@import '../sass/variables'
.map-section
  flex: 1
  display: flex
  position: relative
  height: calc(100vh - 60px)
  .left-navigation
    position: relative
    background-color: $white
    padding-bottom: 6em
    flex-basis: 30%
    min-width: 16em
    display: flex
    flex-direction: column
    .links, .description
      display: flex
    .links
      flex-shrink: 0
      position: sticky
      top: 0
      z-index: 2
      a
        flex: 1
        width: 50%
        justify-content: center
        align-items: center
        display: flex
        box-shadow: 0 2px 4px 0 rgba(22,56,113,0.3)
        height: 43px
        color: $theme-color
        font-weight: bold
        font-size: 14px
        text-decoration: none
        height: 3.3em
        background-color: #FFFFFF
      .router-link-active
        background-color: $light-grey
        box-shadow: none
    .description
      display: flex
      flex-direction: column
      padding: 0 2.5em
      flex-shrink: 1
    .gemeenteBar
      height: 45px
      max-width: 45em
      background-color: #FFFFFF
      box-shadow: 0 2px 4px 0 rgba(22,56,113,0.3)
      .gemeenteNaam
        margin-top: 10px
        margin-left: 60px
        height: 26px
        color: #222222
        font-family: frutigerR
        font-weight: 300
        font-size: 22px
        line-height: 26px
        float: left
      .backButton
        margin-left: 1px
        height: 45px
        width: 45px
        background: linear-gradient(225deg, #033B9A 0%, #000066 100%)
        box-shadow: 0 2px 4px 0 rgba(22,56,113,0.3)
        float: right
        cursor: pointer
        div
          margin-top: 10px
          text-align: center
          color: white

</style>

<style lang="scss" scoped>
.left-navigation {
  overflow-y: scroll;
}
.left-navigation::-webkit-scrollbar {
  width: 10px;
  background-color: white;
}
.left-navigation::-webkit-scrollbar-thumb {
   border-radius: 10px;
   background-color: #000066
}
</style>


Van: Gavin Rehkemper ***@***.***>
Verzonden: donderdag 31 maart 2022 17:48
Aan: Esri/esri-leaflet-renderers ***@***.***>
CC: Mwalima ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Esri/esri-leaflet-renderers] Hi When deploying a docker the package gives this error and does not render a map (Issue #173)


Hi, thank you for reporting this issue. Could you please provide replication case steps to show how to see this issue happening? Also, does the same issue happen when you're not using docker? How are you installing the library? Or are you using the CDN URL?
